Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/money/bank/currencylayer_bank.rb'

Metrics/MethodLength:
  Max: 12

Metrics/LineLength:
  Max: 100

Style/RedundantFreeze:
  Exclude:
    - 'lib/money/bank/currencylayer_bank.rb'
