AllCops:
  TargetRubyVersion: 2.0
  SuggestExtensions: false
  NewCops: 'disable'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/money/bank/currencylayer_bank.rb'

Metrics/MethodLength:
  Max: 12

Metrics/LineLength:
  Max: 120

Style/RedundantFreeze:
  Exclude:
    - 'lib/money/bank/currencylayer_bank.rb'

Style/OptionalBooleanParameter:
  Enabled: false

Security/Open:
  Enabled: false
